In [1]:
import pandas as pd
import numpy as np

In [2]:
stats=pd.read_csv('player_mvp_stats.csv')

In [3]:
stats.head()

,Unnamed: 0,Player,Age,Team,Pos,G,GS,MP,FG,FGA,...,Pts Max,Share,Team_new,W,L,W/L%,GB,PS/G,PA/G,SRS
0,0,A.C. Green,27,Los Angeles Lakers,PF,82,21,26.4,3.1,6.6,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
1,1,Byron Scott,29,Los Angeles Lakers,SG,82,82,32.1,6.1,12.8,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
2,2,Elden Campbell,22,Los Angeles Lakers,PF,52,0,7.3,1.1,2.4,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
3,3,Irving Thomas,25,Los Angeles Lakers,PF,26,0,4.2,0.7,1.9,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73
4,4,James Worthy,29,Los Angeles Lakers,SF,78,74,38.6,9.2,18.7,...,0.0,0.0,Los Angeles Lakers,58,24,0.707,5.0,106.3,99.6,6.73

In [4]:
del stats['Unnamed: 0']

In [5]:
stats.isna().sum()

Player         0
Age            0
Team           0
Pos            0
G              0
GS             0
MP             0
FG             0
FGA            0
FG%           65
3P             0
3PA            0
3P%         2135
2P             0
2PA            0
2P%          110
eFG%          65
FT             0
FTA            0
FT%          582
ORB            0
DRB            0
TRB            0
AST            0
STL            0
BLK            0
TOV            0
PF             0
PTS            0
Year           0
Pts Won        0
Pts Max        0
Share          0
Team_new       0
W              0
L              0
W/L%           0
GB             0
PS/G           0
PA/G           0
SRS            0
dtype: int64

In [6]:
stats[stats["3P%"].isnull()][['Player','3PA']] #players who didnt attempt a 3 pointer dont have a 3 point %

                 Player  3PA
2        Elden Campbell  0.0
3         Irving Thomas  0.0
18           Jack Haley  0.0
20          Keith Owens  0.0
30      Benoit Benjamin  0.0
...                 ...  ...
15782    Evan Eschmeyer  0.0
15783  Gheorghe MureÈ™an  0.0
15785     Jim McIlvaine  0.0
15791  Mark Hendrickson  0.0
15792      Michael Cage  0.0

[2135 rows x 2 columns]

In [7]:
stats=stats.fillna(0)

In [8]:
stats.columns

Index(['Player', 'Age', 'Team', 'Pos', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'Pts Won', 'Pts Max', 'Share', 'Team_new', 'W', 'L', 'W/L%', 'GB',
       'PS/G', 'PA/G', 'SRS'],
      dtype='object')

In [16]:
predictors=[ 'Age', 'G', 'GS', 'MP', 'FG', 'FGA', 'FG%',
       '3P', '3PA', '3P%', '2P', '2PA', '2P%', 'eFG%', 'FT', 'FTA', 'FT%',
       'ORB', 'DRB', 'TRB', 'AST', 'STL', 'BLK', 'TOV', 'PF', 'PTS', 'Year',
       'W', 'L', 'W/L%', 'GB','PS/G', 'PA/G', 'SRS']

In [ ]:
train=stats[stats["Year"]<2024]
test=stats[stats["Year"]==2021]